### ISSUE TITLE
Network connection failure causes auto sniping to fail

### ISSUE THREAD

**Issue by 233635151** [msx752/msniper-location-service#6]
Potentially a network connection failure causes auto sniping to fail. The pokemon count became negative. 

Can the web page tolerates connection failure and re-connect automatically without requiring human to reload the page and re-configure auto sniping?

Thanks.

**Comment by msx752** [comment]
it will takes time.

**Comment by msx752** [comment]
@233635151 now website can re-connect automatically,  
you will know when your connection lost then popup will appear. you only confirm it
