### ISSUE TITLE
[Bug] The site stops updating pokemon list when connected with a identified necrobot

### ISSUE THREAD

**Issue by jambonmcyeah** [msx752/msniper-location-service#7]
### When I have connected my bot to the site, the Pokemon list stopped updating
![image](https://cloud.githubusercontent.com/assets/21069675/20459048/0877dcfc-ae83-11e6-89cc-f8f4c9507c23.png)

**Comment by jambonmcyeah** [comment]
#### It updates just fine when not connected to a identified necrobot

![image](https://cloud.githubusercontent.com/assets/21069675/20459057/5aa0ac7a-ae83-11e6-98ec-7c71d5f37115.png)

**Comment by msx752** [comment]
@jambonmcyeah is bug still continue ?

**Comment by jambonmcyeah** [comment]
@msx752 The bug is fixed now, thanks man
